# Generated by Django 4.0.3 on 2022-09-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followlist', '0002_alter_list_follow_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='follow_user',
            new_name='owner_user',
        ),
    ]
