# Generated by Django 4.0.3 on 2022-09-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followlist', '0004_list_original_id_alter_list_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='original_id',
        ),
    ]
